"""phone required email optional

Revision ID: 9b91379e04cc
Revises: fa3149f38c3c
Create Date: 2026-09-19 13:39:36.121533

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9b91379e04cc'
down_revision = 'fa3149f38c3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.execute(
        sa.text(
            "UPDATE users SET phone_number = '+91' || right("
            "regexp_replace(id::text, '\\D', '', 'g'), 9) "
            "WHERE phone_number IS NULL"
        )
    )
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###