from __future__ import annotations

from enum import Enum


class RoleName(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    FEDERATION_ADMIN = "FEDERATION_ADMIN"
    ADMIN = "ADMIN"
    REGIONAL_ADMIN = "REGIONAL_ADMIN"
    GROUP_ADMIN = "GROUP_ADMIN"
    MEMBER = "MEMBER"


class MemberStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"
    INACTIVE = "INACTIVE"


class EventStatus(str, Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class NewsStatus(str, Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    UNPUBLISHED = "UNPUBLISHED"
    SCHEDULED = "SCHEDULED"


class AdvertisementStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"


class MediaType(str, Enum):
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    DOCUMENT = "DOCUMENT"


class AuditAction(str, Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    REGISTER = "REGISTER"
    PASSWORD_CHANGE = "PASSWORD_CHANGE"
    OTP_REQUEST = "OTP_REQUEST"
    OTP_VERIFY = "OTP_VERIFY"
    OTP_FAILED = "OTP_FAILED"
    MEMBER_CREATE = "MEMBER_CREATE"
    MEMBER_UPDATE = "MEMBER_UPDATE"
    MEMBER_APPROVE = "MEMBER_APPROVE"
    MEMBER_REJECT = "MEMBER_REJECT"
    MEMBER_BLOCK = "MEMBER_BLOCK"
    GROUP_CREATE = "GROUP_CREATE"
    GROUP_UPDATE = "GROUP_UPDATE"
    GROUP_DELETE = "GROUP_DELETE"
    EVENT_CREATE = "EVENT_CREATE"
    EVENT_UPDATE = "EVENT_UPDATE"
    NEWS_CREATE = "NEWS_CREATE"
    NEWS_PUBLISH = "NEWS_PUBLISH"
    ADVERTISEMENT_APPROVE = "ADVERTISEMENT_APPROVE"
    PAYMENT_CREATE = "PAYMENT_CREATE"
    PAYMENT_VERIFY = "PAYMENT_VERIFY"
    ROLE_CHANGE = "ROLE_CHANGE"
    MEDIA_UPLOAD = "MEDIA_UPLOAD"
    MEDIA_DELETE = "MEDIA_DELETE"


class FeeStatus(str, Enum):
    PENDING = "PENDING"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    WAIVED = "WAIVED"
